"""
Django settings for mysite2 project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from	django.utils.translation	import	gettext_lazy	as	_
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wy^(@=wn@0x=m@5q90@%+$*i!qk=7dw84s55f4&%l=)@3ihg^p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','e7885458.ngrok.io',]


# Application definition
INSTALLED_APPS = [
    'accounts',
    'profiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'django_filters',
    'bootstrapform',
    'sorl.thumbnail',

]
THUMBNAIL_DEBUG	=	True
EMAIL_BACKEND	=	'django.core.mail.backends.console.EmailBackend'

# google serive
'''
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_HOST_USER='username@gmail.com/OR/username@coffeehouse.com'
EMAIL_HOST_PASSWORD='password'
EMAIL_USE_TLS=True
'''

 # for filebased backend  EMAIL_FILE_PATH = os.path.join(BASE_DIR,'emails')



AUTH_USER_MODEL = 'accounts.customUser' # changes the built in User model
AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
        'accounts.authenticate.emailAuthBackend',
        'accounts.authenticate.phoneAuthBackend',
        'social_core.backends.facebook.FacebookOAuth2'  ,
        ]


# facebook auth
SOCIAL_AUTH_FACEBOOK_KEY = '2099024307024361'
SOCIAL_AUTH_FACEBOOK_SECRET = '706557f09d756aa5213ef0757f98f55f'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LANGUAGES = (
('en', _('English')),
('ar',_('Arab')),
('fr',_('Frensh')),
    )


ROOT_URLCONF = 'mysite2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'/mysite2/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(os.path.dirname(__file__),'static'),
]
print(STATICFILES_DIRS[0])
MEDIA_ROOT = os.path.join(BASE_DIR,'mysite2/accounts/media/')
MEDIA_URL = '/accounts/media/'
LOCALE_PATHS = (
    os.path.join(BASE_DIR,'locale/'),
)
LOGIN_URL = 'home:login'
LOGOUT_URL ='home:logout'
LOGIN_REDIRECT_URL = 'home:users_posts'
