# Generated by Django 2.0.5 on 2018-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180920_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_not_edited',
            field=models.BooleanField(default='True'),
        ),
    ]
