# Generated by Django 2.0.5 on 2018-09-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_not_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_not_edited',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_edited',
            field=models.BooleanField(default='False'),
        ),
    ]
