# Generated by Django 2.0.5 on 2018-09-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180921_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_edited',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_not_edited',
            field=models.BooleanField(default='True'),
        ),
    ]
