# Generated by Django 2.0.5 on 2018-09-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180926_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowers',
            name='count',
        ),
    ]
